name: Build

on:
  - push
  - pull_request

jobs:
  build_windows:
    strategy:
      matrix:
        os: [windows]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: ./setup.cmd --no-full-poly-car

    - name: Build
      run: ./build.cmd
